CREATE TABLE query_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword TEXT NOT NULL,
    date_offset INTEGER NOT NULL DEFAULT 0,
    start_node VARCHAR(2) NOT NULL DEFAULT '',
    end_node VARCHAR(2) NOT NULL DEFAULT '',
    result_count INTEGER NOT NULL DEFAULT 0,
    ip TEXT NOT NULL DEFAULT '',
    ua_hash VARCHAR(64) NOT NULL DEFAULT '',
    queried_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_query_logs_queried_at ON query_logs (queried_at);
CREATE INDEX idx_query_logs_keyword ON query_logs (keyword);
CREATE INDEX idx_query_logs_combo
    ON query_logs (keyword, date_offset, start_node, end_node, result_count);
CREATE INDEX idx_query_logs_ip_ua ON query_logs (ip, ua_hash);

CREATE TABLE announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    important BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_announcements_created_at ON announcements (created_at DESC);
